---

services:
  homepage:
    container_name: status.services.tygo.van.den.hurk.dev
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    networks:
      - 'proxymesh'
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
      - ./images:/app/public/images
      - ./icons:/app/public/icons
      #// - /var/run/docker.sock:/var/run/docker.sock
    environment:
      PUID: $PUID
      PGID: $PGID
    env_file:
      - path: ./.env
        required: true
    tty: true

networks:
  proxymesh:
    external: true
