---

services:

  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    networks:
      - proxymesh
    volumes:
      - ./config:/app/config
      - ./images:/app/public/images
      - ./icons:/app/public/icons
      #// - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - path: ./.env
        required: true
    tty: true

networks:
  proxymesh:
    external: true
